version: "3.8"
services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
      - "5173:5173"
      - "5174:5174"
    volumes:
      - data:/var/www/html
      - ../web:/workspace/web
      - ../api:/workspace/api
      - ../embed:/workspace/embed
      - ../.vscode:/workspace/.vscode
      
    depends_on:
      - wordpress

 
    networks:
      - app_net

  wordpress:
    image: wordpress:6.6
    restart: always
       
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: omar
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: WPDB
    ports:
      - "8082:80"
    volumes:
      - data:/var/www/html
      - ../quadrillion-wp-plugin:/var/www/html/wp-content/plugins/quadrillion-wp-plugin
 
    networks:
      - app_net
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: WPDB
      MYSQL_USER: omar
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: omar
      PMA_PASSWORD: 123
    networks:
      - app_net

networks:
  app_net:

volumes:
  db_data:
  data: